### ISSUE TITLE
Opção vegana no cardápio diário

### ISSUE THREAD

**Issue by arturspon** [arturspon/UFFS-Bot#42]
A opção de cardápio automático diário, por algum motivo, não mostra a opção vegana do dia.

**Comment by nicolaskribas** [comment]
Fixed in 15d73b896888377cf8e3b5768c49498f203e198f
O problema era que havia uma linha em branco antes da linha com o texto na célula, o bot apenas pegava a primeira linha e então o texto era ignorado.
![image](https://user-images.githubusercontent.com/31111007/64871326-68124680-d61b-11e9-9ebe-d1adf9f412cd.png)

Após a correção o bot exibiu o cardápio corretamente:
![Screenshot_2019-09-13-11-41-55-575_org telegram messenger](https://user-images.githubusercontent.com/31111007/64871911-97758300-d61c-11e9-9704-10d9b6672ffb.png)
Mas tem um espaço em branco que não consegui retirar XD.
